# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_clarifai_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='UpVote_num',
            field=models.IntegerField(default=0),
        ),
    ]
